version: '3.4'

services:

  server:
    image: auth-service
    container_name: "auth-service"
    build: ./
    command: ./app
    ports:
      - 8080:8080
    environment: 
      # Это для того, чтобы было проще проверить работу сервиса. Хранить подобные данные в репозитории конечно не следует
      - GOOGLE_CLIENT_ID=393655468021-enl37tev4gq71gu8eu5huehucsrbpqbt.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=74d6LOUSeH9rMFfXLXWjAfi-